version: '3.7'

services:
  server:
    build:
      dockerfile: ./docker/server.dockerfile
      context: .
    image: meetapp/server
    container_name: meetapp-server
    ports:
      - 3334:3333
    networks:
      - meetapp_network
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules

  queue:
    build:
      dockerfile: ./docker/queue.dockerfile
      context: .
    image: meetapp/queue
    container_name: meetapp-queue
    ports:
      - 3335:3333
    networks:
      - meetapp_network
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules

  redis:
    image: redis:alpine
    container_name: meetapp-redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - meetapp_network
  postgres:
    image: postgres
    container_name: meetapp-postgres
    restart: always
    ports:
      - '5433:5432'
    networks:
      - meetapp_network
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  meetapp_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
